Repository CampusDual/2023-BBE-1-G2, pull requests merged in 2023-06, with the labels that each got.

#15 adding country in hotel
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/HotelDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
Labels: feat

#16 Adding prices and validations in room and booking
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/BookingDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/RoomDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/RoomService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/BookingDao.xml
  jardhotelsontimize/pom.xml
Labels: feat

#18 G2 56
  db/2023-BBE-1-G2.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/RoomService.java
Labels: feat

#19 adding tests
  jardhotelsontimize/jardhotelsontimize-model/pom.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/GuestService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/RoomService.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/BookingServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/GuestServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/HotelServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/RoomServiceTest.java
  jardhotelsontimize/pom.xml
Labels: test

#20 G2-51
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/service/ICountryService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/CountryDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/CountryService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/GuestService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/RoomService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/CountryDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/BookingServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/GuestServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/HotelServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/RoomServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/CountryRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
Labels: feat

#21 testing
  jardhotelsontimize/jardhotelsontimize-ws/pom.xml
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/test/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestControllerTest.java
Labels: test

#25 G2-95-Testing - Adding filters and its testing
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/BookingServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/RoomRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/test/java/com/campusdual/jardhotelsontimize/ws/core/rest/RoomRestControllerTest.java
Labels: feat

#26 arreglados bugs, detalles en descipcion
  db/2023-BBE-1-G2.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/CheckinGreaterThanCheckout.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/CheckinLowerThanCurrentDate.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/ForbiddenOperation.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/GuestNotFound.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/HotelNotFound.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/NotUniqueRoomNumber.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/OverlappingBooking.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/exceptions/RoomNotFound.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/CountryService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/GuestService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/RoomService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/BookingDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/BookingServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/GuestServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/HotelServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/RoomServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/test/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestControllerTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/test/java/com/campusdual/jardhotelsontimize/ws/core/rest/RoomRestControllerTest.java
Labels: bug

#29 latitude and longitude in hotels
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/HotelDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/HotelServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
Labels: feat
