Repository CampusDual/2023-BBE-1-G2, pull requests merged in 2023-07, with the labels that each got.

#32 G2 94
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/service/IUserRoleService.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/service/IUserService.java
  jardhotelsontimize/jardhotelsontimize-boot/src/main/java/com/campusdual/jardhotelsontimize/ServerApplication.java
  jardhotelsontimize/jardhotelsontimize-boot/src/main/resources/application.yml
  jardhotelsontimize/jardhotelsontimize-model/src/main/db/templateDB.script
  jardhotelsontimize/jardhotelsontimize-model/src/main/db/templateDB.txt
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/PersonDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/StaffDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/UserDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/UserRoleDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BankAccountService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/CountryService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/GuestService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/JobService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/PersonService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/RoomService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/StaffService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/UserRoleService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/UserService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/RoleDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/RoleServerPermissionDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/ServerPermissionDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/UserDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/UserRoleDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/PersonServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/RoomServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/StaffServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/UserRoleRestController.java
  jardhotelsontimize/pom.xml
Labels: feat

#33 Updating Phone
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
Labels: bug

#34 Adding check-in check-out
  db/2023-BBE-1-G2.sql
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/BookingDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/BookingDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/BookingServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/GuestServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/PersonServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/StaffServiceTest.java
Labels: feat

#35 G2 100
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/BookingDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/BookingService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/BookingDao.xml
Labels: feat

#36 adding door security system
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/RoomRestController.java
Labels: feat

#37 adding phone to the hotel and its patterns
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
Labels: feat

#40 G2 109
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/pom.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/model/TouristicPlace.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/HotelService.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/BookingServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
  jardhotelsontimize/pom.xml
Labels: bug, feat

#42 Adding Menu
  db/2023-BBE-1-G2.sql
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/service/IMenuService.java
  jardhotelsontimize/jardhotelsontimize-api/src/main/java/com/campusdual/jardhotelsontimize/api/core/service/IPantryService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/MenuDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/dao/PantryDao.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/GuestService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/MenuService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/PantryService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/PersonService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/StaffService.java
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/MenuDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/main/resources/dao/PantryDao.xml
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/MenuServiceTest.java
  jardhotelsontimize/jardhotelsontimize-model/src/test/java/com/campusdual/jardhotelsontimize/model/core/service/PantryServiceTest.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/MenuRestController.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/PantryRestController.java
Labels: feat

#43 adding security in pantry insert and delete
  db/Inserts.sql
  db/JARDHotelsOntimize.postman_collection.json
  jardhotelsontimize/jardhotelsontimize-model/src/main/java/com/campusdual/jardhotelsontimize/model/core/service/PantryService.java
  jardhotelsontimize/jardhotelsontimize-ws/src/main/java/com/campusdual/jardhotelsontimize/ws/core/rest/HotelRestController.java
Labels: bug
